on:
  pull_request:
    types: [ opened, synchronize ]
  issue_comment:
    types: [ created, edited ]

jobs:
  click-up-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4

      - name: Parse task id from branch name
        id: task-id-from-branch
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          TASK_ID=$(python script/parse_task_id.py $BRANCH_NAME)
          
          echo ::set-output name=TASK_ID::$TASK_ID

      - name: Parse task id from comment
        id: task-id-from-comment
        run: |
          COMMENT_BODY=${{ github.event.comment.body }}
          TASK_ID=$(echo "$COMMENT_BODY" | sed "s/^CU-//g")
          echo ::set-output name=TASK_ID::$TASK_ID

      - name: Sync task status
        run: |
          TASK_ID=${{ steps.task-id-from-branch.outputs.TASK_ID || steps.task-id-from-comment.outputs.TASK_ID }}
          if [ $TASK_ID ]; then
              curl -i -X PUT \
              "https://api.clickup.com/api/v2/task/$TASK_ID" \
              -H "Authorization: $CLICKUP_TOKEN" \
              -H 'Content-Type: application/json' \
              -d '{ "status": "ON-HOLD" }'
          else
              echo "No task ID found in branch name or comment"
              exit 0
          fi

        env:
          CLICKUP_TOKEN: ${{ secrets.CLICKUP_TOKEN }}

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Task ${{ steps.task-id-from-branch.outputs.TASK_ID || steps.task-id-from-comment.outputs.TASK_ID }} is now ON-HOLD
